### ISSUE TITLE
Add ability to sync upload to FTP

### ISSUE THREAD

**Issue by bwibwi13** [ftpgrab/ftpgrab#26]
I am currently using ftp-sync to backup the content of one FTP server to a local folder.
It would be great if we could use it to backup a local folder to a remote FTP server.

I have not yet digged deeper into the script, but I am hoping that replacing wget by wput would allow to do that easily.

What do you think?

**Comment by crazy-max** [comment]
This improvement requires lot of refactoring and for the moment i don't have time for this.
But your are welcome to open a PR if you want to work on it ;)

**Comment by bwibwi13** [comment]
OK. I will take a look at what I can propose.
But I will probably have some questions in order to make the right decisions.

First question, how would you see this being configured?
We could use the DL_METHOD parameter and set it to "wput", for example?
Or would you prefer to use a totally new parameter?

**Comment by crazy-max** [comment]
Yep that's sounds good, i'm working on the [4.0 milestone](/crazy-max/ftp-sync/milestone/1) for now so if you have time i can include this improvement.

**Comment by crazy-max** [comment]
This issue has been closed because it has been inactive for a long time.
But we can always reopen it though!
