### ISSUE TITLE
How to exclude .part

### ISSUE THREAD

**Issue by bentux** [ftpgrab/ftpgrab#27]
Hi Crazy-max,

How can I exclude tha .part files?

Thanks for all

**Comment by crazy-max** [comment]
Hi, for the moment there is no exclude filter.
Will be implemented on the next release

**Comment by bentux** [comment]
Thanks for the reply

**Comment by bentux** [comment]
Hi Crazy-max,
Any news about this?

**Comment by crazy-max** [comment]
Hi @bentux, sorry for the late i'm currently working on an other project.
I think i can solve your issue by the end of the month.

**Comment by bentux** [comment]
Many thanks :)
What's about your other project? Maybe it could be intresting for us. ;)

**Comment by crazy-max** [comment]
I'm currently working on two projects, there is neard, a portable wamp software stack (http://neard.io) ans Geass, a multi-user front-end client for rTorrent with many features (https://github.com/crazy-max/geass)

**Comment by crazy-max** [comment]
Some screenshots for Geass: https://plus.google.com/collection/0Datx

**Comment by bentux** [comment]
Intresting projects ;)
So it is possible to name files *.part during the transfert with ftp-sync?

**Comment by airainchoc** [comment]
May I ask if you made any progress on this ? 

Thanks

**Comment by crazy-max** [comment]
Hi, i will work on it next week.

**Comment by airainchoc** [comment]
Thanks :)

**Comment by crazy-max** [comment]
Hi, i have started to work on it, i keep you in touch

**Comment by crazy-max** [comment]
Hi guys, the latest release 4.3.0 include this feature : https://ftpgrab.github.io/news/2017-12-26-ftpgrab-4.3.0-available/
