### ISSUE TITLE
wget error 4

### ISSUE THREAD

**Issue by mbc0** [ftpgrab/ftpgrab#31]
Sorry of this is the wrong place to ask but I cannot find anywhere else!

I have just installed ftpgrab but cannot get it to work? 

If I try a manual wget command to download a file it works fine but I cannot get ftpgrab to work due to a wget error 4, can someone please look over my log to see if there is anything obviously wrong? 

I have *** out my username and password purposely

Many Thanks!

FTPGrab v4.1.1 (rapidseedbox - 2017/10/11 01:09:12
--------------
Config: rapidseedbox
Script PID: 5508
Log file: /var/log/ftpgrab/rapidseedbox-20171011010912.log
FTP sources count: 1
FTP secure: 0
Download method: wget
Resume downloads: 0
Shuffle file/folder list: 0
Hash type: md5
Hash storage: text
Hash file: /opt/ftpgrab/hash/rapidseedbox.txt
--------------
#DEBUG FTP_SRC: /Downloads/
#DEBUG DIR_DEST: /home/ubuntuvm/unraidserver/processingfolder/ubuntuvmsync
#DEBUG DIR_DEST_REF: /home/ubuntuvm/unraidserver/processingfolder/ubuntuvmsync/
Source: ftp://**.**.**.**/Downloads/
Destination: /home/ubuntuvm/unraidserver/processingfolder/ubuntuvmsync/
Checking connection to ftp://**.**.**.**/Downloads/...
#DEBUG checkConnection: wget --spider -q --tries=1 --timeout=5 --ftp-user=***** --ftp-password=********** -O - ftp://**.**.**.**/Downloads/
ERROR: Wget error 4
More infos: http://www.gnu.org/software/wget/manual/html_node/Exit-Status.html

**Comment by crazy-max** [comment]
Hi,

Can you post your ftpgrab config plz (without your credentials ofc) ?
