### ISSUE TITLE
Files downloaded again (with hash already in database)

### ISSUE THREAD

**Issue by mickael-bertrand** [ftpgrab/ftpgrab#32]
Hi ! 

For several days, some files that have already been downloaded are downloaded again (with the same hash). I noticed that on small files (sfv, nfo), the problem doesn't happen.
If you have any idea what the cause of the problem is, I would be grateful:) 
I dont understand, because ftpgrab work fine since few weeks and since few day it doesnt work properly :s 
I try to upgrade from 4.1 to 4.2, it doesn't change anything. I try to remove all ftpgrab files (db, config) and reinstall it.
I try with file storage for hash.

### Steps to reproduce this issue

- Start a download sync with ftpgrab
- remove downloaded files from destination but keep files from source(ftp)
- re-sync with ftpgrap 
- The files already downloaded before are downloaded again (same hash)...

### Expected Behaviour
it should not download again the files with the same hash

#### Actual Behaviour
it download file with when the hash is preent in the sqlite database

#### Configuration

**Operating system and platform (ex.Debian 8 64bits)** :
Mint 64bits

**ftpgrab version (ex. 3.0)** :
4.1 and the same error after upgrading to 4.2

**wget version (ex. 1.16)** :
GNU Wget 1.17.1 compilé sur linux-gnu

**curl version (ex. 7.38.0)** :
7.47.0

**md5sum / sha1sum version (ex. 8.23)** :
sha1sum (GNU coreutils) 8.25

**sqlite3 version (ex. 3.8.7.1)** :
3.11.0 2016-02-15

----

Some logs with a file was already in database and already downloaded : 

FTPGrab v4.2.1 (**** - 2017/10/29 05:00:02)
--------------
Config: ****
Script PID: 5351
Log file: /var/log/ftpgrab/****-20171029050002.log
FTP sources count: 1
FTP secure: 1
Download method: curl
Resume downloads: 0
Shuffle file/folder list: 0
Hash type: sha1
Hash storage: sqlite3
Hash file: /opt/ftpgrab/hash/****.db
--------------
#DEBUG FTP_SRC: /***/TERMINE/***/DOWNLOAD/
#DEBUG DIR_DEST: /media/***/****
#DEBUG DIR_DEST_REF: /media/***/****/
Source: ftp://***.***.com:/***/TERMINE/***/DOWNLOAD/
Destination: /media/***/****/
Checking connection to ftp://***.***.***:/***/TERMINE/***/DOWNLOAD/...
#DEBUG checkConnection: curl --silent --retry 1 --retry-delay 5 --globoff -u ***:*** --ftp-ssl --insecure ftp://***.***.com:/***/TERMINE/***/DOWNLOAD/
Successfully connected!
#DEBUG checkfolder: curl --silent --list-only --globoff -u *****:***** --ftp-ssl --insecure "ftp://***.***.com:/***/TERMINE/***/DOWNLOAD/%5f1080/"
#DEBUG lineClean: _1080/
#DEBUG basename: _1080
#DEBUG srcfile: /***/TERMINE/***/DOWNLOAD/_1080
#DEBUG srcfileproc: /***/TERMINE/***/DOWNLOAD/%5f1080
#DEBUG srcfileshort: _1080
#DEBUG srcfileshort2: _1080
#DEBUG srchash: 778870d88b238ebea917bbd03af402b8a0d11fe5
#DEBUG srcsize: 
#DEBUG destfile: /media/****/****/_1080
#DEBUG destsize: N/A
#DEBUG vregex: _1080
#DEBUG checkfolder: curl --silent --list-only --globoff -u *****:***** --ftp-ssl --insecure "ftp://***.***.com:/****/TERMINE/****/DOWNLOAD/%5f1080/%5b%20********%20%5d%20****.2017.MULTi.1080p.BluRay.x264%2dLOST.mkv/"
#DEBUG lineClean: [ ******* ] ****.2017.MULTi.1080p.BluRay.x264-LOST.mkv
#DEBUG basename: [ ******** ] ****.2017.MULTi.1080p.BluRay.x264-LOST.mkv
#DEBUG srcfile: /****/TERMINE/****/DOWNLOAD/_1080/[ ******** ] ****.2017.MULTi.1080p.BluRay.x264-LOST.mkv
#DEBUG srcfileproc: /****/TERMINE/****/DOWNLOAD/%5f1080/%5b%20********%20%5d%20****.2017.MULTi.1080p.BluRay.x264%2dLOST.mkv
#DEBUG srcfileshort: _1080/[ ******** ] ****.2017.MULTi.1080p.BluRay.x264-LOST.mkv
#DEBUG srcfileshort2: _1080/[ ******** ] ****.2017.MULTi.1080p.BluRay.x264-LOST.mkv
#DEBUG srchash: aa5c5b6f229f96719be96073bf11ad850b0a4ed9
#DEBUG srcsize: 8526998229
#DEBUG destfile: /media/****/****/_1080/[ ******** ] ****.2017.MULTi.1080p.BluRay.x264-LOST.mkv
#DEBUG destsize: N/A
#DEBUG vregex: _1080/[ ******** ] ****.2017.MULTi.1080p.BluRay.x264-LOST.mkv
Process file: _1080/[ ******** ] ****.2017.MULTi.1080p.BluRay.x264-LOST.mkv
Hash: aa5c5b6f229f96719be96073bf11ad850b0a4ed9
Size: 7.94 Gb
Status: Never downloaded...
Start download to /media/****/****/_1080/[ ******** ] ****.2017.MULTi.1080p.BluRay.x264-LOST.mkv... Please wait...
#DEBUG Download command: curl --globoff -u *****:***** --ftp-ssl --insecure "ftp://***.***.com:/***/TERMINE/****/DOWNLOAD/%5f1080/%5b%20********%20%5d%20****.2017.MULTi.1080p.BluRay.x264%2dLOST.mkv" -o "/media/****/****/_1080/[ ******** ] ****.2017.MULTi.1080p.BluRay.x264-LOST.mkv"

**Comment by crazy-max** [comment]
Hi,

Ok so the src filename is `_1080/[ ******** ] .2017.MULTi.1080p.BluRay.x264-LOST.mkv` with hash `aa5c5b6f229f96719be96073bf11ad850b0a4ed9`.

Can you check on [this website](http://www.sha1-online.com/) if the hash is correct ?
If not, can you paste the real filename plz ?

**Comment by mickael-bertrand** [comment]
HI Crazy-max, 

> #DEBUG lineClean: [ Torrent9.tv ] Cars.3.2017.MULTi.1080p.BluRay.x264-LOST.mkv
> #DEBUG basename: [ Torrent9.tv ] Cars.3.2017.MULTi.1080p.BluRay.x264-LOST.mkv
> #DEBUG srcfile: /TORRENT/TERMINE/TORRENT/DOWNLOAD/_FILMS1080/[ Torrent9.tv ] Cars.3.2017.MULTi.1080p.BluRay.x264-LOST.mkv
> #DEBUG srcfileproc: /TORRENT/TERMINE/TORRENT/DOWNLOAD/%5fFILMS1080/%5b%20Torrent9.tv%20%5d%20Cars.3.2017.MULTi.1080p.BluRay.x264%2dLOST.mkv
> #DEBUG srcfileshort: _FILMS1080/[ Torrent9.tv ] Cars.3.2017.MULTi.1080p.BluRay.x264-LOST.mkv
> #DEBUG srcfileshort2: _FILMS1080/[ Torrent9.tv ] Cars.3.2017.MULTi.1080p.BluRay.x264-LOST.mkv
> #DEBUG srchash: aa5c5b6f229f96719be96073bf11ad850b0a4ed9

sha1 for srcfileshort is the same hash   aa5c5b6f229f96719be96073bf11ad850b0a4ed9

thanks for your help.

**Comment by crazy-max** [comment]
Ok can you post your hash file plz ?

**Comment by mickael-bertrand** [comment]
[seedbox.db.zip](https://github.com/ftpgrab/ftpgrab/files/1425472/seedbox.db.zip)
Here is the sqlite file. 
for this file : 
"27"	"27"	"aa5c5b6f229f96719be96073bf11ad850b0a4ed9"	"_FILMS1080/[ Torrent9.tv ] Cars.3.2017.MULTi.1080p.BluRay.x264-LOST.mkv"

**Comment by mickael-bertrand** [comment]
I tried with two files containing spaces or not, it's the same thing.

**Comment by crazy-max** [comment]
Hi, you right, there is an issue!
Thanks for your input, i will investigate on this.

**Comment by crazy-max** [comment]
@mickael-bertrand Should be solved in the latest release ;)

**Comment by mickael-bertrand** [comment]
Thanks @crazy-max.
In the meantime, if you know a possible workaround, I'd be interested. 
Have a nice day.

**Comment by mickael-bertrand** [comment]
Sorry i didnt see the new release :). 
I just tried it and it works perfectly.
Thank you very much for your reactivity

**Comment by crazy-max** [comment]
Hi @mickael-bertrand !
Your welcome and thanks a lot for your donation, it is much appreciated :)
