### ISSUE TITLE
line 73 and line 88 [: too many arguments

### ISSUE THREAD

**Issue by airainchoc** [ftpgrab/ftpgrab#35]
I was getting an error while executing the script (/usr/bin/ftpgrab: line 73: [: too many arguments), but I found the solution:

in /usr/bin/ftpgrab, 
line 73:
change:
`         if [ "$HASH_STORAGE" == "text" ] && [ -z $(grep "^$_SRC_HASH" "$HASH_FILE") ]`
to:
`        if [ "$HASH_STORAGE" == "text" ] && [[ -z $(grep "^$_SRC_HASH" "$HASH_FILE") ]]`

line 88:
change:
`    if [ "$HASH_STORAGE" == "text" ] && [ ! -z $(grep "^$_SRC_HASH" "$HASH_FILE") ]`
to:
`   if [ "$HASH_STORAGE" == "text" ] && [[ ! -z $(grep "^$_SRC_HASH" "$HASH_FILE") ]]`

Maybe you could do it directly in your next release :)

**Comment by crazy-max** [comment]
Hi @airainchoc, this duplicate the issue #34
But thanks for your input!

**Comment by crazy-max** [comment]
Has been solved in the latest release (4.3.1)
