### ISSUE TITLE
ftpgrab trying to download unfinished downloads

### ISSUE THREAD

**Issue by mbc0** [ftpgrab/ftpgrab#37]
Hi,

I love this little program, it works very very well for me except I am getting failures due to ftpgrab trying to download a file from my ftp that has not finished downloading.. is there a way around this?

Many Thanks!

**Comment by crazy-max** [comment]
Hi @mbc0,

FTPGrab does not read the status of the file to see if it is opened by another program. Therefore, you should download first to a temporary folder and then move it to the folder that will be used by FTPGrab. Are you using rTorrent? Maybe it's also related to issue #32? Please let me know. Thank you

**Comment by mbc0** [comment]
Hi, it is not related to issue #32 it's answered as you say by not reading the status of a file to check if it is open or not.  I use ftp grab to download from rutorrent with no issues, but I also use it to download the output directory of a handbrake auto conversion docker which quite often has uncomplete encodes in it. ftpgrab tries 3 times then gives up then tries again in an hour so not the end of the world!  Thanks for getting back to me.

**Comment by crazy-max** [comment]
Yes this is a very old and well-known problem with the FTP protocol. What we can do is recover the size of the file and check 5 seconds later if its size has not changed.

**Comment by mbc0** [comment]
No worries, I understand, thank you for replying! :-)

**Comment by crazy-max** [comment]
No problme, i will make a slight modification to solve this problem or at least detect it.

**Comment by mbc0** [comment]
fantastic!! Thanks!!

**Comment by mbc0** [comment]
Hey mate, did you have any joy with this? :-)

**Comment by crazy-max** [comment]
Hey @mbc0, check the latest release ;)

**Comment by mbc0** [comment]
Mate, you are a star! it works perfectly! such a great program, thanks so much :-)
