### ISSUE TITLE
nawk on DS216j / DSM 6.1.6-15266 Update 1

### ISSUE THREAD

**Issue by daemqn** [ftpgrab/ftpgrab#38]
Hi, 

nawk is not available on DSM 6.1.6-15266 Update 1.
I installed entware but its not there too.
I commented the nawk part on the script and it seems to be fine though.
Thanks for your great script anyway :)

**Comment by crazy-max** [comment]
Indeed, `nawk` is not required anymore. I will update the script, thanks for your input and support!

**Comment by daemqn** [comment]
thanks
and update the requirements ;)

**Comment by crazy-max** [comment]
Solved in 4.3.3 release
