### ISSUE TITLE
Ignore files by date?

### ISSUE THREAD

**Issue by lochstar** [ftpgrab/ftpgrab#39]
Hi,

I was wondering if there was a way to set ftpgrab to only look at files in a directory, starting from a particular date?

I'd like to set it up to monitor a remote dir, but don't need it pulling in a bunch of files that exist remotely that I have already downloaded and sorted.

Thanks for the help.

**Comment by crazy-max** [comment]
Hi,

It's a feasable feature, i put this in my backlog
Thanks for your input

**Comment by crazy-max** [comment]
@lochstar Available in the latest release
