### ISSUE TITLE
Always getting Status: Hash sum exists. Skip download...

### ISSUE THREAD

**Issue by evosolnet** [ftpgrab/ftpgrab#40]
I seem to get this result when trying to download a file with the same name as one previously downloaded.  However I know that the file has changed, and the sha1sum does not match what is in the hash db.  The output even indicates the file size is different, but displays an incorrect sha1sum than if I download the file and run sha1sum filename

**Comment by crazy-max** [comment]
Hi,

Please read and apply [SUPPORT.md](https://github.com/ftpgrab/ftpgrab/blob/master/.github/SUPPORT.md) page
Thanks

**Comment by crazy-max** [comment]
Closed due to inactivity
