### ISSUE TITLE
ftpgrab restarts automatically after being killed

### ISSUE THREAD

**Issue by daemqn** [ftpgrab/ftpgrab#41]
Hi, 

I can't get ftpgrab to stop after killing it.
The process always starts again
Thanks

**Comment by crazy-max** [comment]
Hi,

Just use the `kill(1)` command but instead of giving it a process number, give it the negation of the group number. For example to kill every process in group 5112, use `kill -TERM -- -5112`.

Src: https://stackoverflow.com/a/392155/514571
