### ISSUE TITLE
add ftpgrab train command

### ISSUE THREAD

**Issue by gregf** [ftpgrab/ftpgrab#46]
It would be nice if I could point ftpgrab to a directory of files and it would hash them so it wouldn't download them again. Sometimes it's not as simple as setting a date on from when to grab. I think this would be a nice way to train it before you use it so it's not downloading anything you already have.

**Comment by crazy-max** [comment]
@gregf FTPGrab already set hash of files based on their paths inside a Bolt database to prevent download them again. Do you talk about something like #12 ?

**Comment by gregf** [comment]
No, before I start using the program to download stuff I want to pass it my local tv directory have it index all those files, then start downloading and have it not download anything I have locally.

**Comment by crazy-max** [comment]
This is already the case, see https://github.com/ftpgrab/ftpgrab/blob/master/internal/app/ftpgrab.go#L172-L175
