### ISSUE TITLE
Is support config charset like GB2312?

### ISSUE THREAD

**Issue by foolin** [ftpgrab/ftpgrab#50]
### Behaviour

A chinese ftp server, the folder like "中文目录",  it can't create the correct directory.

#### Steps to reproduce this issue

1. A ftp server set charset GB2312
2. use ftpgrab

### Configuration

* FTPGrab version (5.0.0) :  5.3.0
* Platform (windows/linux/freebsd/macos) :  linux
* Remote FTP (Pure-FTPd) or SFTP (OpenSSH) server:  security and private, sorry!

### Logs

> FTPGrab logs (set --log-level flag to debug and --log-ftp)
```
Mon, 03 Jun 2019 08:50:52 UTC INF --------
Mon, 03 Jun 2019 08:50:52 UTC INF Checking /2018������/����/����-EXP-201812.rar
Mon, 03 Jun 2019 08:50:52 UTC INF Never downloaded
Mon, 03 Jun 2019 08:50:52 UTC INF Downloading file (10.15MB) to /data/�/����-EXP-201812.rar...
Mon, 03 Jun 2019 08:50:52 UTC ERR Cannot create destination dir error="mkdir /data/2018������: invalid argument"
Mon, 03 Jun 2019 08:50:52 UTC INF Time spent: 3 milliseconds
Mon, 03 Jun 2019 08:50:53 UTC INF --------
Mon, 03 Jun 2019 08:50:53 UTC INF Checking /2019������/����͢/����͢-EXP-201901.rar
Mon, 03 Jun 2019 08:50:53 UTC INF Never downloaded
Mon, 03 Jun 2019 08:50:53 UTC INF Downloading file (10.3MB) to /data/2019������/����͢/����͢-EXP-201901.rar...
Mon, 03 Jun 2019 08:50:53 UTC ERR Cannot create destination dir error="mkdir /data/2019������: invalid argument"
Mon, 03 Jun 2019 08:50:53 UTC INF Time spent: 3 milliseconds
Mon, 03 Jun 2019 08:50:53 UTC INF --------
Mon, 03 Jun 2019 08:50:53 UTC INF Checking /2019������/����͢/����͢-EXP-201902.rar
Mon, 03 Jun 2019 08:50:53 UTC INF Never downloaded
Mon, 03 Jun 2019 08:50:53 UTC INF Downloading file (10.02MB) to /data/2019������/����͢/����͢-EXP-201902.rar...
Mon, 03 Jun 2019 08:50:53 UTC ERR Cannot create destination dir error="mkdir /data/2019������: invalid argument"
Mon, 03 Jun 2019 08:50:53 UTC INF Time spent: 3 milliseconds
```

![image](https://user-images.githubusercontent.com/2344587/58789652-39023700-8621-11e9-8be4-42af2fc38213.png)

**Comment by foolin** [comment]
I had fork and support GBK at: https://github.com/foolin/ftpgrab


@crazy-max I can PR if necessary~~

**Comment by crazy-max** [comment]
Hi @foolin,

> I forked and support GBK at: https://github.com/foolin/ftpgrab

I looked at your changes quickly and I would have some suggestions to solidify the implementation.

> I can PR if necessary~~

Yes sure, feel free to open a PR!

**Comment by crazy-max** [comment]
@foolin Can you try the latest release (5.5.0) ? I have made some changes on a fork of goftp module (see #55)

**Comment by foolin** [comment]
Good! Thanks!

**Comment by vgdh** [comment]
cp1251 is also not supported
