### ISSUE TITLE
New feature suggestions

### ISSUE THREAD

**Issue by ynqjwsm** [ftpgrab/ftpgrab#57]
ftpgrab is a great software, but in the process of using, I hope to add the following features：

1. finished check，detecting whether the file has been written，such as delay detection file size（First check the file size once, and then check it again after 10 seconds. If the two sizes are equal, the file is completed.），suffix filtering（just like sample.txt and sample.txt.writting），ok file check（There is an sample.ok file indicating that the sample.txt file is completed. ）etc.
2. path Expression support，Expressions are allowed in the path，just like /data/{yyyyMMdd}/ or  Regular expression like /data//^\d{8}^//
3. execute command after file transfer completed, and support some built-in parameters ，like file path ,size etc....

**Comment by crazy-max** [comment]
Hi @ynqjwsm,

1. I think the suffix filtering would be good enough. I could implement a delay detection when #48 will be fixed.
2. If you talk about sources paths yes we can do that.
3. For each file? Do you have a use case?

Thanks for your suggestions!
