### ISSUE TITLE
POST for Webhook

### ISSUE THREAD

**Issue by hongkongkiwi** [ftpgrab/ftpgrab#58]
Hi there,

Firstly, thank you for an excellent piece of software that does an amazing job of something that so many people need! I really appreciate the authors effort here.

For my use case, there is one small feature missing which is POST support for the webhook.

The use case is to send a slack message upon completion of the sync. Sending a SLACK message requires some params (notably some info about the message content design etc). 

It looks like only GET is supported from the docs?

Alternatively, if I can have an external bash script to be called after ftpgrab completion, I could have a simple shell script to scrape the .log file and then post that as a slack message. I saw this in another issue #57

**Comment by crazy-max** [comment]
Hi @hongkongkiwi,

You can already set POST method (see [webhook documentation](https://ftpgrab.github.io/doc/configuration/#webhook)).
And thanks for your support!

**Comment by hongkongkiwi** [comment]
Hi, perhaps I missed it but I couldn't see any documentation about the POST format for the webhook? I can only see GET mentioned. Did I miss something?

```
webhook
enable: Enable webhook notification (default: false).
endpoint: URL of the HTTP request. required
method: HTTP method (default: GET). required
headers: Map of additional headers to be sent.
timeout: Timeout specifies a time limit for the request to be made. (default: 10).
```

**Comment by crazy-max** [comment]
@hongkongkiwi, you have to set `method; POST`, that's it :)
The body structure will look like [this](https://ftpgrab.github.io/doc/faq/#whats-the-structure-of-the-webhook-notification).
