### ISSUE TITLE
Multiple FTP instances

### ISSUE THREAD

**Issue by marccolemont** [ftpgrab/ftpgrab#61]
I have been searching this forum but don't find the answer here unless I overlooked.
I want to use FTPgrab on a Synology NAS to sync automatically multiple Hyperdeck Mini video recorders (which have an internal FTP server) to the NAS. Each recorder will get its own directory. 
- Can I configure multiple directories / IP addresses with one FTPgrab instance? Or do I need to run multiple FTPgrab's for each of the FTP servers (recorders) in the network?
- I need to sync ONLY as soon as a video is finished recording aka not growing in size anymore. I found this request #57 related to that. The recorder also writes an extra .mcc file with the same name as soon as a recording is finished. That could also be a way to check.
Thanks for your help.

**Comment by crazy-max** [comment]
> Can I configure multiple directories / IP addresses with one FTPgrab instance? Or do I need to run multiple FTPgrab's for each of the FTP servers (recorders) in the network?

You can only configure one provider. But what you can do is creating one config file for each servers and launch multi instances of FTPGrab:

```
ftpgrab --config server1.yml
ftpgrab --config server2.yml
...
```

> I need to sync ONLY as soon as a video is finished recording aka not growing in size anymore. I found this request #57 related to that. The recorder also writes an extra .mcc file with the same name as soon as a recording is finished. That could also be a way to check.

Yes indeed, #57 covers this enhancement. For now can you instead move files to a _complete_ folder and grab from them?

**Comment by marccolemont** [comment]
Thanks for the reply.

Moving files manually on the loaded SD cards on the Hyperdeck recorder would require a second FTP access, and it doesn’t allow that. Just tried again FTP connections are lost until reboot when I try with 2 users on the same device.
Hmm … What I then need for the time being is a way to manual trigger ftpgrab to check for new files after a session has been recorded on the Hyperdecks.
It are video guys operating not IT guys. So they need some simply GUI to trigger a sync, preferably a webinterface. 
Like I'm using a tool that I also run on the Synology NAS. Hyperdeck Panel - that sends network commands to the recorders through a webinterface for gang-recording and easy access.
http://hyperdeck.iamjeffamato.com/
I could add some buttons there to trigger a sync on ftpgrab right after a recording STOP command has been send. But ftpgrab runs on a timer. Is there a way to change the timer dynamically to a high / low value? As I assume ftpgrab reads the timer value only during startup  from the config file.
Giving it more thought, It would also lower unnecessary network traffic and requests to these recorders while they are recording.

**Comment by crazy-max** [comment]
Ok so I think it's enough if we cover #62 for your use case.
