### ISSUE TITLE
Documentation/Functionality Mismatch

### ISSUE THREAD

**Issue by craigkc** [ftpgrab/ftpgrab#69]
### Behaviour
In the ftpgrab.yml file, the implementation of the parsing of "timeout" is different between FTP and SFTP and doesn't match documentation.

#### Steps to reproduce this issue

1. Configure a ftpgrab.yml FTP block with "**timeout: 30**" which will succeed.

2. Configure a ftpgrab.yml FTP block with "**timeout: 30s**" which will fail with error="unable to decode into struct, yaml: unmarshal errors:\n  line 15: cannot unmarshal !!str `
30s` into int"

3. Configure a ftpgrab.yml SFTP block with "**timeout: 30**" which will fail with error="unable to decode into struct, yaml: unmarshal errors:\n  line 36: cannot unmarshal !!int `
30` into time.Duration"

4. Configure a ftpgrab.yml SFTP block with "**timeout: 30s**" which will succeed.

#### Expected behaviour

I prefer the implementation in the SFTP block over the FTP block, but they should at least be consistent and match the documentation.  The marshaling to datatype time.duration allows for more clarity and improved UX.  The documentation should be updated to indicate the use of "30s" to indicate 30 seconds, and the code for the parsing of the FTP block should be updated to match that of the SFTP block.

#### Actual behaviour

For FTP, the value must be an integer such as "30" just as the documentation shows.  For SFTP, the value must be an expression of time.duration such as "30s" which the documentation does not indicate.

### Configuration

* FTPGrab version: 6.2.0
* Platform: QNAP NAS w/ Container Station (Docker)
* Remote FTP: Irrelevant

### Logs

Fri, 17 Jan 2020 22:10:11 UTC FTL Cannot load configuration error="unable to decode into struct, yaml: line 37: could not find expected ':'"                 
Fri, 17 Jan 2020 22:10:33 UTC INF Starting FTPGrab 6.2.0                                                                                                     
Fri, 17 Jan 2020 22:10:33 UTC FTL Cannot load configuration error="unable to decode into struct, yaml: unmarshal errors:\n  line 36: cannot unmarshal !!int `
30` into time.Duration"                                                                                                                                      
Fri, 17 Jan 2020 22:11:14 UTC INF Starting FTPGrab 6.2.0                                                                                                     
Fri, 17 Jan 2020 22:11:14 UTC FTL Cannot load configuration error="unable to decode into struct, yaml: unmarshal errors:\n  line 36: cannot unmarshal !!int `
5` into time.Duration"                                                                                                                                       
Fri, 17 Jan 2020 22:11:27 UTC INF Starting FTPGrab 6.2.0                                                                                                     
Fri, 17 Jan 2020 22:11:27 UTC FTL Cannot connect to server error="cannot open ssh connection, dial tcp: i/o timeout"                                         
Fri, 17 Jan 2020 22:12:53 UTC INF Starting FTPGrab 6.2.0                                                                                                     
Fri, 17 Jan 2020 22:12:53 UTC FTL Cannot connect to server error="tls: first record does not look like a TLS handshake"                                      
Fri, 17 Jan 2020 22:13:18 UTC INF Starting FTPGrab 6.2.0                                                                                                     
Fri, 17 Jan 2020 22:13:18 UTC FTL Cannot load configuration error="unable to decode into struct, yaml: unmarshal errors:\n  line 15: cannot unmarshal !!str `
30s` into int"

**Comment by crazy-max** [comment]
Hi @craigkc,

Indeed this is linked to go-yaml/yaml@9e32271 introduced in yaml v3. I will make some changes about this. Thanks for your input.

**Comment by crazy-max** [comment]
@craigkc Should be ok with latest release

**Comment by craigkc** [comment]
I haven't used the Webhook function, so good catch unifying it as well.  Thanks for the quick update, even though my report was incredibly minor!
